// +build ignore

package main

import (
	"bytes"
	"go/format"
	"io/ioutil"
	"os"
	"strings"
)

var lengthFunction = `// Len return the length of this skip set.
// Keep in sync with types_gen.go:lengthFunction
// Special case for code generation, Must in the tail of skipset.go.
func (s *Int64Set) Len() int {
	return int(atomic.LoadInt64(&s.length))
}`

func main() {
	f, err := os.Open("skipset.go")
	if err != nil {
		panic(err)
	}
	byte, err := ioutil.ReadAll(f)
	if err != nil {
		panic(err)
	}

	w := new(bytes.Buffer)
	w.WriteString(`// Code generated by go run types_gen.go; DO NOT EDIT.` + "\r\n")
	w.WriteString(string(byte)[strings.Index(string(byte), "package skipset") : strings.Index(string(byte), ")\n")+1])
	ts := []string{"Float32", "Float64", "Int32", "Int", "Uint32", "Uint64", "Uint"}
	for _, upper := range ts {
		lower := strings.ToLower(upper)
		data := string(byte)
		// Remove header.
		data = data[strings.Index(data, ")\n")+1:]
		// Remove the special case.
		data = strings.Replace(data, lengthFunction, "", -1)
		// Common cases.
		data = strings.Replace(data, "int64", lower, -1)
		data = strings.Replace(data, "Int64", upper, -1)
		if strings.Index(lower, "float") == 0 || lower == "int" || lower == "int32" || lower == "uint" || lower == "uint32" || lower == "uint64" {
			data = strings.Replace(data, "length "+lower, "length int64", 1)
			data = strings.Replace(data, "atomic.Add"+upper, "atomic.AddInt64", -1)
		}
		// Add the special case.
		data = data + strings.Replace(lengthFunction, "Int64Set", upper+"Set", 1)
		w.WriteString(data)
		w.WriteString("\r\n")
	}

	out, err := format.Source(w.Bytes())
	if err != nil {
		panic(err)
	}
	if err := ioutil.WriteFile("types.go", out, 0660); err != nil {
		panic(err)
	}
}
